# ./docker-compose.yml

web:
  build: .
  dockerfile: Dockerfile # That's our Dockerfile path
  env_file: .env # Set environment variables from an `.env` file, if needed
  command: mix phoenix.server # Start the server if no other command is specified

  volumes:
    - .:/app # Here we're mounting our project's root directory inside the container
  ports:
    - "4000:4000"
  links:
    - postgres

#test:
#  image: rumbl_web # We're just using the already built `web` image here
#  env_file: .env
#  command: mix test # Run the entire test suite if no other command is specified
#  environment:
#    - MIX_ENV=test # That's key
#    - PORT=4001
#    - PG_HOST=postgres
#    - PG_USERNAME=postgres
#  volumes_from:
#    - web
#  links:
#    - postgres

postgres:
  image: postgres:latest # https://hub.docker.com/_/postgres/
  ports:
    - "5433:5432"
  volumes:
    - ./data:/var/lib/postgresql/data

